<a href="https://colab.research.google.com/github/Danxi3/GuzmanDaniella_BSIS2/blob/main/1stExercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import numpy as np
data = np.array([1,2,3,4,5])
print(np.median(data))

3.0


In [26]:
mean = np.mean(data)

In [27]:
print(mean)

3.0


In [28]:
median = np.median(data)

In [29]:
print(median)

3.0


In [31]:
median = np.median(data)

In [32]:
print(mean)

3.0


In [33]:
median = np.median(data)

In [34]:
print(median)

3.0


In [35]:
max = np.max(data)

In [36]:
print(max)

5


In [38]:
stv_dev = np.std(data)

In [39]:
print(std_dev)

0.816496580927726


In [40]:
total = np.sum(data)

In [41]:
print(total)

15


In [42]:
reshaped_array = data.reshape((5,1))

In [43]:
print(reshaped_array)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [44]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
concatenated = np.concatenate((array1,array2))

In [45]:
print(concatenated)

[1 2 3 4 5 6]


In [50]:
range_array = np.arange(0,10,2)

In [51]:
print(range_array)

[0 2 4 6 8]
