<a href="https://colab.research.google.com/github/Danxi3/GuzmanDaniella_BSIS2/blob/main/1stExercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
data = np.array([1,2,3,4,5])
print(np.median(data))

3.0


In [ ]:
mean = np.mean(data)

In [ ]:
print(mean)

3.0


In [ ]:
median = np.median(data)

In [ ]:
print(median)

3.0


In [ ]:
median = np.median(data)

In [ ]:
print(mean)

3.0


In [ ]:
median = np.median(data)

In [ ]:
print(median)

3.0


In [ ]:
max = np.max(data)

In [ ]:
print(max)

5


In [ ]:
stv_dev = np.std(data)

In [ ]:
print(std_dev)

0.816496580927726


In [ ]:
total = np.sum(data)

In [ ]:
print(total)

15


In [ ]:
reshaped_array = data.reshape((5,1))

In [ ]:
print(reshaped_array)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [ ]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
concatenated = np.concatenate((array1,array2))

In [ ]:
print(concatenated)

[1 2 3 4 5 6]


In [ ]:
range_array = np.arange(0,10,2)

In [ ]:
print(range_array)

[0 2 4 6 8]
